// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjW0E0hxvVRevshPIJbo8CrsfPOzfttKc',
    appId: '1:360007186412:web:ca716b86308e7e4e24b2c9',
    messagingSenderId: '360007186412',
    projectId: 'babubhaiyaa-a69f2',
    authDomain: 'babubhaiyaa-a69f2.firebaseapp.com',
    storageBucket: 'babubhaiyaa-a69f2.appspot.com',
    measurementId: 'G-JYDNZ8DB15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApKeKhh0LymUj-Xg0gNiV5thfZQj4sZ4A',
    appId: '1:360007186412:android:70367743f1be38cf24b2c9',
    messagingSenderId: '360007186412',
    projectId: 'babubhaiyaa-a69f2',
    storageBucket: 'babubhaiyaa-a69f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNu3xH7PHNcerGH7qEVIVB5ThjkcAwJJA',
    appId: '1:360007186412:ios:02c78959c9245f3924b2c9',
    messagingSenderId: '360007186412',
    projectId: 'babubhaiyaa-a69f2',
    storageBucket: 'babubhaiyaa-a69f2.appspot.com',
    iosBundleId: 'com.example.flutterTestproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNu3xH7PHNcerGH7qEVIVB5ThjkcAwJJA',
    appId: '1:360007186412:ios:6174fa98c74528c424b2c9',
    messagingSenderId: '360007186412',
    projectId: 'babubhaiyaa-a69f2',
    storageBucket: 'babubhaiyaa-a69f2.appspot.com',
    iosBundleId: 'com.example.flutterTestproject.RunnerTests',
  );
}
